### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by dimzon** [EsotericSoftware/reflectasm#23]
http://pastebin.com/SZi1MRZd

seems like reflection outperforms ReflectASM  >8[]

**Comment by hepin** [comment]
using jmh do the benchmark
https://github.com/ktoso/sbt-jmh
https://github.com/scalameter/scalameter

**Comment by NathanSweet** [comment]
We should definitely use JMH for any future benchmarks.

Unsafe is set to be unsupported in future Java versions. Currently Kryo tries unsafe, then ReflectASM, then falls back to reflection. It would be nice if ReflectASM could handle doing that, plus the new way of doing it in Java 9+. If the new built-in API is the fastest, ReflectASM would be obsolete when using newer JVMs.

**Comment by NathanSweet** [comment]
Closing for reasons explained here:
https://github.com/EsotericSoftware/reflectasm/issues/24#issuecomment-396297372
