### ISSUE TITLE
Does not support Java 8

### ISSUE THREAD

**Issue by Pyrolistical** [EsotericSoftware/reflectasm#35]
This project embeds 4.2 of ow2 asm, but that only supports Java 7:

http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftags%2FASM_4_2%2Fsrc%2Forg%2Fobjectweb%2Fasm%2FClassReader.java
` if (readShort(off + 6) > Opcodes.V1_7) {`

An upgrade to 5.0 or greater will solve this problem.  This also implies Apache Spark does not support Java 8 as it depends on this project.

**Comment by Pyrolistical** [comment]
Back link to the Spark issue https://issues.apache.org/jira/browse/SPARK-6152

**Comment by HiJon89** [comment]
Should be fixed by #33, not sure when that will be relased though

**Comment by magro** [comment]
I just pushed this with reflectasm-1.10.1 to maven central.
