### ISSUE TITLE
Revisit maven shading/release strategy

### ISSUE THREAD

**Issue by jhaber** [EsotericSoftware/reflectasm#36]
Currently reflectasm releases a JAR with a transitive dependency on ASM as

``` xml
<groupId>com.esotericsoftware</groupId>
<artifactId>reflectasm</artifactId>
<version>1.10.0</version>
```

and a JAR with ASM bundled and relocated as

``` xml
<groupId>com.esotericsoftware</groupId>
<artifactId>reflectasm</artifactId>
<version>1.10.0</version>
<classifier>shaded</classifier>
```

This causes some minor headaches such as the shaded JAR sharing a POM with the original JAR so it still has a transitive dependency on ASM which needs to be excluded. But more importantly, using a classifier changes the maven coordinates. This makes it possible to have both the normal and shaded JAR end up in your dependency tree. It also makes it impossible to use Maven's `dependencyManagement` facility to control whether you want the normal or shaded JAR. 

I think it would be better to distinguish the shaded JAR with a version suffix, something like `1.10.0-shaded`. By using the same maven coordinates, you're guaranteed that you only have either the normal or shaded JAR in your dependency tree, and it's easy to control which one you get through dependency management without needing to resort to exclusions and other hackery

**Comment by NathanSweet** [comment]
@magro Can you weigh in?

**Comment by magro** [comment]
Related: #54

**Comment by NathanSweet** [comment]
@magro Looks like we can close this with #54 and #60.

**Comment by jhaber** [comment]
Works for me, thanks a lot
