### ISSUE TITLE
Array indexing messed up on reload

### ISSUE THREAD

**Issue by HansPeeterTulmin** [EsotericSoftware/reflectasm#37]
The reflected classes are stored in an array whose ordering is changed on code reload(JRebel). The API seems to rely on this ordering.
This causes ArrayIndexOutOfBoundsException(class at index 6, length also 6) or undefined behaviour(want to load class a, get b instead).
Updating indices on array change should fix the problem.

**Comment by NathanSweet** [comment]
What array? Updating indices when?
