### ISSUE TITLE
AsmDex support

### ISSUE THREAD

**Issue by OleksandrKucherenko** [EsotericSoftware/reflectasm#38]
Is it possible to change abstraction in way lib will become independent from Asm implementation?
I mean will it be possible to use AsmDex instead of original Asm library?

more info: 
- http://asm.ow2.org/doc/tutorial-asmdex.html
- https://github.com/crittercism/dexmaker

**Comment by NathanSweet** [comment]
I doubt it. The bytecodes are very low level and specific the VM. I wonder
if you could convert the Java bytecodes from ReflectASM to dex on the fly.
That might be the way to go.
