### ISSUE TITLE
not support overload

### ISSUE THREAD

**Issue by initeasylife** [EsotericSoftware/reflectasm#48]
ResultSet _rs=....
MethodAccess _rsAccess = MethodAccess.get(_rs.getClass());
_rsAccess.invoke(_rs, "getBlob", 1)     //correct
_rsAccess.invoke(_rs, "getBlob", "id") //error
 java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

**Comment by NathanSweet** [comment]
We now have methods that take a Class[] of parameter types.
https://github.com/EsotericSoftware/reflectasm/blob/master/src/com/esotericsoftware/reflectasm/MethodAccess.java#L38
