### ISSUE TITLE
MethodAccess.getIndex lookup of incorrect method definition index

### ISSUE THREAD

**Issue by pranasblk** [EsotericSoftware/reflectasm#55]
There are 2 methods:

- int getStrategyName(byte[] dest, int destOffset)
- CharSequence getStrategyName() 

_Actual result:_ 
MethodAccess.getIndex("getStrategyName") picks up the incorrect one.

_Expected result:_
Index of second definition must be retrieved if no parameters specified.

**Comment by pranasblk** [comment]
_Current work around:_
access.getIndex(getterName, new Class[] {})

_and fall back to (for more similar potential issus):_
final Method reflect = clazz.getDeclaredMethod(getterName);
return reflect.invoke(e);

**Comment by NathanSweet** [comment]
Per the javadocs, `getIndex(String)` "Returns the index of the first method with the specified name." You need to specify the parameters if your method has multiple names. It may be nice to sort the methods by number of arguments, please feel free to make a PR if you'd like that.
