### ISSUE TITLE
Deploy 1.11.6 to Maven Central

### ISSUE THREAD

**Issue by hepin1989** [EsotericSoftware/reflectasm#60]
http://mvnrepository.com/artifact/com.esotericsoftware/reflectasm

Only 1.11.3 is listed here.

**Comment by NathanSweet** [comment]
Likely those releases were done only on GitHub. @magro maybe it's time for a 1.11.6 Maven release? I think Kryo needs an updated ReflectASM.

**Comment by magro** [comment]
@NathanSweet see my comment here: https://github.com/EsotericSoftware/reflectasm/issues/54#issuecomment-396382619
