### ISSUE TITLE
OSGi import org.objectweb.asm;version="[5.1,6)"

### ISSUE THREAD

**Issue by swimmesberger** [EsotericSoftware/reflectasm#68]
The library defines the "Import-Package: org.objectweb.asm;version="[5.1,6)"" MANIFEST.MF header even though the asm library is shaded and therefore no import is needed.

**Comment by NathanSweet** [comment]
@magro I guess we need to use a different manifest for the shaded JAR?

**Comment by magro** [comment]
We need to customize the maven bundle plugin as it seems, to exclude the asm import (not sure if an osgi classloader allows access from com.esotericsoftware.reflectasm to com.esotericsoftware.asm though). Alternatively we could remove the bundle plugin and manually add the appropriate manifest entries via custom configuration of the jar plugin (this way it's explicit what's written to the manifest, what I'd regard as an advantage). 

I'm currently on vacation and therefore cannot work on this before next week.

**Comment by magro** [comment]
> I guess we need to use a different manifest for the shaded JAR?

I assumed that there's only a single reflectasm artifact/jar released, which has asm shaded (instead of two artifacts, where only one has asm shaded). Not sure if that's your understanding as well @NathanSweet, because you're referring to "the shaded JAR".

**Comment by NathanSweet** [comment]
Sorry, I haven't kept track on how you are doing the artifacts (since I don't use them). I thought we were doing both shaded and not shaded, but it's not for me anyway so whatever you are doing is fine, carry on. :)

**Comment by swimmesberger** [comment]
A statement like:
<Import-Package>!org.objectweb.asm.*</Import-Package>

in the pom.xml, maven-bundle-plugin instructions might be enough.
This would tell bnd (the base of the mave-bundle-plugin) to simply exclude this package from the Import-Package metadata.

**Comment by magro** [comment]
@swimmesberger Do you want to submit a PR for this?
