### ISSUE TITLE
Class versions V1_5 or less must use F_NEW frames.

### ISSUE THREAD

**Issue by isMeiying** [EsotericSoftware/reflectasm#70]

**Comment by NathanSweet** [comment]
Can you make a PR showing what you would like changed?

**Comment by isMeiying** [comment]
@NathanSweet I am very sorry, it is my problem: after I cloned the code, I replaced asm with the latest “org.ow2.asm:asm:7.2-beta”, causing problems.

**Comment by isMeiying** [comment]
Thank you~
