### ISSUE TITLE
class loaded by urlclassloader and cannot be cast to com.esotericsoftware.reflectasm.MethodAccess

### ISSUE THREAD

**Issue by ppgf135** [EsotericSoftware/reflectasm#71]
hi,
   we load a class by 
`          URL url = new URL(modelUrl);
                URL[] urls = new URL[]{url};
                loader = new URLClassLoader(urls);
                cls = loader.loadClass(className);`

and when it  execute at "MethodAccess.get(cls)"  it throws an ClassCastException

![image](https://user-images.githubusercontent.com/4034708/61506173-d66bcb80-aa13-11e9-9610-cfc8543fcfa6.png)

**Comment by ppgf135** [comment]
<dependency>
        <groupId>com.esotericsoftware</groupId>
        <artifactId>reflectasm</artifactId>
        <version>1.11.9</version>
    </dependency>

**Comment by NathanSweet** [comment]
You'll need to provide an SSCCE so I can debug the problem: http://sscce.org/
If you can provide that I'll reopen this issue.
