### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by icoco** [EsotericSoftware/reflectasm#80]
this lib if can use on Android ?

while I use it in Android code , it report error while running :

`java.lang.UnsupportedOperationException: can't load this type of class file
W/System.err:     at java.lang.ClassLoader.defineClass(ClassLoader.java:591)`

**Comment by NathanSweet** [comment]
It should work on Android. Not sure what that error is about, sorry.

**Comment by icoco** [comment]
i see, let me check then,thanks__
