### ISSUE TITLE
Failure of test testAutoUnloadClassloaders

### ISSUE THREAD

**Issue by pgrt** [EsotericSoftware/reflectasm#82]
Hello,

When building release 1.11.6 in a clean Debian/unstable chroot with openjdk-11, I get a failure of testAutoUnloadClassloaders due to its last assertion:

[INFO] Running com.esotericsoftware.reflectasm.ClassLoaderTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.18 s <<< FAILURE! - in com.esotericsoftware.reflectasm.ClassLoaderTest
[ERROR] testAutoUnloadClassloaders(com.esotericsoftware.reflectasm.ClassLoaderTest)  Time elapsed: 0.174 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<1> but was:<0>
        at com.esotericsoftware.reflectasm.ClassLoaderTest.testAutoUnloadClassloaders(ClassLoaderTest.java:89)

I am unsure about it, but it might be linked to the garbage collector, with which the test fiddles just before?

Thanks for your help,
Pierre

**Comment by NathanSweet** [comment]
The test can fail based on GC behavior. `reclaimLoaders` can't be sure the GC really cleans up entries from the WeakHashMap used by `AccessClassLoader.activeAccessClassLoaders()`. It's not a great test, but I'm not sure it can be better.

**Comment by pgrt** [comment]
Hello,

Thanks for your explanations! It's clear to me. I also feel it should be hard to get something better, because of the GC behaviour.
So I'm closing the issue.

Thanks again,
Pierre
